### PR TITLE
mylibrary: show only my resources (fixes #3567)

### LINKED ISSUE #3567: automatically move a downloaded file to myLibrary
when a resource is successfully downloaded from library move it to myLibrary for learners who is already a member

https://github.com/open-learning-exchange/myplanet/assets/64019708/263d0d70-ae4c-42fb-adff-09ce839df5a9

### PR DESCRIPTION
**Pull request by ewhang5**
@Okuro3499 please review when possible

### CODE REVIEW

**Comment by Okuro3499** [comment]
@ewhang5 follow the code on this listener https://github.com/open-learning-exchange/myplanet/blob/a697985d4a860eed9544a588c3e8e4349f801c44/app/src/main/java/org/ole/planet/myplanet/ui/resources/ResourceDetailFragment.kt#L141 and ensure you pass to the on add method in not null

**Comment by ewhang5** [comment]
fixes #3567

**Comment by ewhang5** [comment]
fixed Gideon's concern

https://github.com/open-learning-exchange/myplanet/assets/59347000/3459b0d8-e924-4361-9a33-5a9765165ae9

**Comment by Okuro3499** [comment]
@ewhang5 I think you misunderstood me. The resources within the courses are the ones if downloaded should be added to myLibrary onDownloadComplete not courses added to myCourses

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
@ewhang5 I thing you misunderstood me. In courses we also have resources attached to the course the idea was to add the resources to myLibrary onDownloadComplete. Your solution adds courses to mycourses onDownloadComplete

**Review by rlam20 — CHANGES_REQUESTED** [review]
resources downloaded from the course don't show up in myResources

**Comment by ewhang5** [comment]
@Okuro3499 addressed your revision.

https://github.com/open-learning-exchange/myplanet/assets/59347000/c8060336-56da-46ab-9bba-8aff2a2220b4

**Review by rlam20 — APPROVED** [review]

**Review by strawberrybread — APPROVED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
