### PR TITLE
update apk(Fixes #1357 )

### LINKED ISSUE #1357: only prompt to update with condition
if `http://address/versions` -> latestapk is equal to `http://address/apkversion` 
Screenshot 2019-11-15 at 5 10 27 PM

`Same as`
Screenshot 2019-11-15 at 5 10 43 PM

### PR DESCRIPTION
**Pull request by rrijal53**

### CODE REVIEW

**Comment by rrijal53** [comment]
@leomaxi  please provide feedback i m little confused with the logic.

**Comment by rrijal53** [comment]
@leomaxi please review

**Comment by rrijal53** [comment]
@leomaxi  it is working for me.

**Comment by leomaxi** [comment]
https://github.com/open-learning-exchange/myplanet/pull/1455

**Pull request closed without merging**
