### PR TITLE
Sort member list (Fixes #1821 )

### LINKED ISSUE #1821: Health: No option to sort by name
I get the idea behind sorting by the most recent, but this is only makes sense when the health worker creates a new patient record and wants to access that immediately.

Otherwise sorting by name makes a lot more sense.  Ideally there would be an option to sort the list in different ways.

### PR DESCRIPTION
**Pull request by rrijal53**
#1821 
device-2020-06-12-203902

### CODE REVIEW

**Comment by anthonyhvo12** [comment]
@rrijal53 It would be better if the created dates and titles of the users are also displayed next to their names. A sort by name option would also be helpful.

**Comment by rrijal53** [comment]
@leomaxi @anthonyhvo12  please check now 
device-2020-06-12-213952

**Comment by anthonyhvo12** [comment]
@rrijal53 The Order By Name options were missing asc/dsc. I have fixed that.

**Comment by rrijal53** [comment]
> @rrijal53 The Order By Name options were missing asc/dsc. I have fixed that.

thanks

**Comment by anthonyhvo12** [comment]
On my planet, the only user with a profile picture is "anthonytest", but here it is displayed on other users' rows, too.
[Screen Shot 2020-06-12 at 12 45 33 PM](https://user-images.githubusercontent.com/43098273/84526106-ba67bd00-acaa-11ea-977a-7f43e337cf2c.png)
Screen Shot 2020-06-12 at 12 46 10 PM

**Pull request merged**
