### PR TITLE
resources: safer transactions  (fixes #3645)

### LINKED ISSUE #3645: IllegalStateException
```
Exception java.lang.IllegalStateException: no event down from INITIALIZED in component ResourcesFragment{86efa2b} (1a5cdcaa-8513-47b4-8694-f95c2e16d8ab id=0x7f0a0224 tag=shelf)
  at androidx.lifecycle.LifecycleRegistry.moveToState (LifecycleRegistry.kt:126)
  at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent (LifecycleRegistry.kt:119)
  at androidx.fragment.app.Fragment.performDestroy (Fragment.java:3352)
  at androidx.fragment.app.FragmentStateManager.destroy (FragmentStateManager.java:781)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:335)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1890)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1817)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1760)
  at androidx.fragment.app.FragmentManager$5.run (FragmentManager.java:547)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at androidx.test.espresso.base.Interrogator.loopAndInterrogate (Interrogator.java:10)
  at androidx.test.espresso.base.UiControllerImpl.loopUntil (UiControllerImpl.java:7)
  at androidx.test.espresso.base.UiControllerImpl.loopUntil (UiControllerImpl.java:1)
  at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent (UiControllerImpl.java:5)
  at androidx.test.espresso.action.MotionEvents.sendUp (MotionEvents.java:6)
  at androidx.test.espresso.action.MotionEvents.sendUp (MotionEvents.java:1)
  at androidx.test.espresso.action.Tap.sendSingleTap (Tap.java:5)
  at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap
  at androidx.test.espresso.action.Tap$1.sendTap (Tap.java:1)
  at androidx.test.espresso.action.GeneralClickAction.perform (GeneralClickAction.java:4)
  at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform (ViewInteraction.java:2)
  at androidx.test.espresso.ViewInteraction.doPerform (ViewInteraction.java:23)
  at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform
  at androidx.test.espresso.ViewInteraction$1.call (ViewInteraction.java:6)
  at androidx.test.espresso.ViewInteraction$1.call (ViewInteraction.java:1)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7870)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
```

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #3645

test using roboscripts choose this as test device 
Screenshot 2024-07-05 at 17 40 12

### CODE REVIEW

**Review by strawberrybread — APPROVED** [review]

**Review by rlam20 — APPROVED** [review]

**Comment by ewhang5** [comment]
Ran a new workflow and got a new aab/apk for this branch. Used the aab in a robotest with the small device, but it failed with the following error. Will request changes for now, but I am not sure why I got this crash. Let me know if I tested this PR incorrectly

Screenshot 2024-07-08 at 9 57 02 AM

**Review by ewhang5 — CHANGES_REQUESTED** [review]
See comment above

**Comment by Okuro3499** [comment]
@ewhang5 share the roboscript you used on discord

**Comment by Okuro3499** [comment]
@ewhang5 this is a new error not related to this fix copy and paste the error to create a new issue

**Review by dogi — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
