### PR TITLE
Video streaming issue fixed (Fixes #463)

### LINKED ISSUE #463: Video File Download
In the image below there is video resource
screenshot_1546616979
Clicking on Download button of Video resource takes you to video player instead of download
screenshot_1546616957
Also video player is not playing video at all. This resource works from planet. Tested some of video resources and it was same.
screenshot_1546616964

### PR DESCRIPTION
**Pull request by rrijal53**

### CODE REVIEW

**Comment by leomaxi** [comment]
Video resource seems to be downloaded. But doesn't play.. Does it try to play directly or stream.. I am confused with the . word used stream.

**Comment by rrijal53** [comment]
@leomaxi  When you try to open video that is not downloaded, app will stream video online. And if the video file is downloaded it try to play the video directly.

**Comment by leomaxi** [comment]
@rrijal53 Thant is what i am not getting to work. Those downloaded should play at least.. Let me try to debug it and revert the PR.

**Comment by leomaxi** [comment]
Error
`01-08 16:40:46.987 22147-22345/org.ole.planet.myplanet E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
01-08 16:40:47.008 22147-22348/org.ole.planet.myplanet I/OMXClient: Using client-side OMX mux.
01-08 16:40:47.031 22147-22349/org.ole.planet.myplanet I/SoftAAC2: limiting to stereo output
01-08 16:40:47.032 22147-22349/org.ole.planet.myplanet I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
01-08 16:40:47.052 22147-22346/org.ole.planet.myplanet E/SoftAVC: Decoder failed: -2
01-08 16:40:47.053 22147-22345/org.ole.planet.myplanet E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
    signalError(omxError 0x80001001, internalError -2147483648)
01-08 16:40:47.054 22147-22344/org.ole.planet.myplanet E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
01-08 16:40:47.061 22147-22342/org.ole.planet.myplanet E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:758)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
01-08 16:40:47.079 22147-22342/org.ole.planet.myplanet E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:628)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:512)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:439)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:468)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:341)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:150)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:972)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:772)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
01-08 16:40:47.238 22147-22187/org.ole.planet.myplanet D/EGL_emulation: eglMakeCurrent: 0xae434dc0: ver 2 0
`

**Comment by leomaxi** [comment]
It might be from the resource filename. Like this ones filename is bad (it has . , spaces) 
`
تصحيح  مضخة الصوديوم والبوتاسيوم.54mp4.mp4`

screenshot 2019-01-08 at 6 39 24 pm

**Comment by leomaxi** [comment]
Working now. :+1

**Pull request merged**
