### PR TITLE
chat: mark shared (fixes #3734)

### LINKED ISSUE #3734: duplicate shared chat
shared chat is still shareable causing duplicated shared chat

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #3734

Screenshot_20240628_142705

### CODE REVIEW

**Review by rlam20 — COMMENTED** [review]
Looks good but the check mark won't display until the page is refreshed

**Review by ewhang5 — CHANGES_REQUESTED** [review]
agree with @rlam20

**Comment by Okuro3499** [comment]
ok will work on that

**Comment by ewhang5** [comment]
@Okuro3499 still doesn't work for me. Attaching a screen recording of what I am testing:

https://github.com/open-learning-exchange/myplanet/assets/59347000/955734a0-010e-4813-b5aa-bace8c541900

**Review by rlam20 — COMMENTED** [review]
Looks good. A future improvement could be having the option to share again or share to multiple teams/communities.

**Review by rlam20 — APPROVED** [review]

**Review by strawberrybread — APPROVED** [review]

**Review by ewhang5 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
