### PR TITLE
settings: smoother languages in dark mode (fixes #3977)

### LINKED ISSUE #3977: dark mode in other languages
in other languages user not able to set app theme
[Screen_recording_20240731_184634.webm](https://github.com/user-attachments/assets/93150f05-bf2a-4f03-95be-e1ea9f985609)

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #3977

### CODE REVIEW

**Review by ewhang5 — CHANGES_REQUESTED** [review]
Crashes when opening settings:
Screenshot 2024-07-31 at 1 17 02 PM

**Comment by rlam20** [comment]
> Crashes when opening settings: Screenshot 2024-07-31 at 1 17 02 PM

the fix for this is #3978 which hasn't been merged yet

**Comment by Okuro3499** [comment]
@ewhang5 branch is rebased. test again

**Review by ewhang5 — APPROVED** [review]
The subtext for dark mode, "Set the App Theme to Dark Mode or Back to Normal" is still not translated, but functionality works well.

**Review by rlam20 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
