### PR TITLE
welcome: new onboarding screens (fixes #2329)

### LINKED ISSUE #2329: add onboarding screens

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #2329
chromebook
Screenshot 2023-09-04 15 22 27
Screenshot 2023-09-04 15 22 39
Screenshot 2023-09-04 15 22 46
Screenshot 2023-09-04 15 24 48

mobile
Screenshot_20230904_152415_myPlanet
Screenshot_20230904_152422_myPlanet
Screenshot_20230904_152427_myPlanet
Screenshot_20230904_152432_myPlanet

### CODE REVIEW

**Review by Mutugiii — DISMISSED** [review]
Looks good

**Review by Mutugiii — COMMENTED** [review]
On the tablet, the message at the end of the page is cutoff.

Screenshot_20230824_203110_myPlanet

**Review by Mutugiii — COMMENTED** [review]
Like how it looks, though there is a very tiny cutoff:

Screenshot_20230907_154132_myPlanet

**Comment by Mutugiii** [comment]
Also on mobile devices, landscape mode all the text is cutoff(Not sure we want to address it)

Screenshot_20230907_154821_myPlanet

**Review by dogi — APPROVED** [review]

**Pull request merged**
