### PR TITLE
all: smoother feedback list dark mode (fixes #4454)

### LINKED ISSUE #4454: feedback cards incompatible w dark mode
image

### PR DESCRIPTION
**Pull request by Kuljeet1998**
Fixes: #4454

### CODE REVIEW

**Comment by Kuljeet1998** [comment]
@deeppp15 @Okuro3499  could you please check if its working in light mode? On the preview, the changes are being reflected, but on my phone its not. Could you guys please test and let me know.

**Comment by Okuro3499** [comment]
@Kuljeet1998 in darkmode it works but in light mode it's still dark
Screenshot_20240923_215001

**Comment by Okuro3499** [comment]
@Kuljeet1998 in the master branch even before we do any changes the card seem to have a grey background I haven't been able to figure out where it's being set but checking this could be the first step

**Comment by deeppp15** [comment]
Hi @Kuljeet1998 

In my phone the light mode seems fine but the problem is in darkmode. 

0fd79f65-a88b-4b0f-8f26-47c42dce7ebe


08e5bbd7-75b2-4c7e-a917-d94779bd6203

**Comment by Kuljeet1998** [comment]
Working fine now @deeppp15 @Okuro3499 
image
image

**Review by deeppp15 — APPROVED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
