### PR TITLE
teams: smoother permissions (fixes #3889)

### LINKED ISSUE #3889: only team members should be able to alter team data

### PR DESCRIPTION
**Pull request by ewhang5**
fixes #3889

### CODE REVIEW

**Review by rlam20 — CHANGES_REQUESTED** [review]
image
I'm able to assign tasks to people on a team that I'm not a part of. Is that out of the scope of this issue?

**Comment by ewhang5** [comment]
> image I'm able to assign tasks to people on a team that I'm not a part of. Is that out of the scope of this issue?

No that should have been fixed. Did you leave the team and then try to assign tasks? Or were you already not a part of the team but it still allowed you to assign tasks?

**Comment by ewhang5** [comment]
> > > image I'm able to assign tasks to people on a team that I'm not a part of. Is that out of the scope of this issue?
> > 
> > 
> > No that should have been fixed. Did you leave the team and then try to assign tasks? Or were you already not a part of the team but it still allowed you to assign tasks?
> 
> I wasn't part of the team originally and it still allowed me to assign tasks

Can you see if the other teams are having the same issue for you? For me, I am a part of okuro team, but the other teams that I am not a part of do not allow me to assign tasks.

**Comment by rlam20** [comment]
> > > > image I'm able to assign tasks to people on a team that I'm not a part of. Is that out of the scope of this issue?
> > > 
> > > 
> > > No that should have been fixed. Did you leave the team and then try to assign tasks? Or were you already not a part of the team but it still allowed you to assign tasks?
> > 
> > 
> > I wasn't part of the team originally and it still allowed me to assign tasks
> 
> Can you see if the other teams are having the same issue for you? For me, I am a part of okuro team, but the other teams that I am not a part of do not allow me to assign tasks.

Happens on Tech Pioneers as well 
image

**Comment by ewhang5** [comment]
> > > > > image I'm able to assign tasks to people on a team that I'm not a part of. Is that out of the scope of this issue?
> > > > 
> > > > 
> > > > No that should have been fixed. Did you leave the team and then try to assign tasks? Or were you already not a part of the team but it still allowed you to assign tasks?
> > > 
> > > 
> > > I wasn't part of the team originally and it still allowed me to assign tasks
> > 
> > 
> > Can you see if the other teams are having the same issue for you? For me, I am a part of okuro team, but the other teams that I am not a part of do not allow me to assign tasks.
> 
> Happens on Tech Pioneers as well image

This is what my side looks like for Tech Pioneers which I am also not a member of. Could you double check you are on the correct branch?
Screenshot 2024-07-25 at 3 23 44 PM

**Comment by rlam20** [comment]
> > > > > > image I'm able to assign tasks to people on a team that I'm not a part of. Is that out of the scope of this issue?
> > > > > 
> > > > > 
> > > > > No that should have been fixed. Did you leave the team and then try to assign tasks? Or were you already not a part of the team but it still allowed you to assign tasks?
> > > > 
> > > > 
> > > > I wasn't part of the team originally and it still allowed me to assign tasks
> > > 
> > > 
> > > Can you see if the other teams are having the same issue for you? For me, I am a part of okuro team, but the other teams that I am not a part of do not allow me to assign tasks.
> > 
> > 
> > Happens on Tech Pioneers as well image
> 
> This is what my side looks like for Tech Pioneers which I am also not a member of. Could you double check you are on the correct branch? Screenshot 2024-07-25 at 3 23 44 PM

that's my fault, i didn't pull the changes. looks good

**Review by rlam20 — APPROVED** [review]

**Review by strawberrybread — APPROVED** [review]

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
i'm still able to alter the reports in enterprises
maybe also disabling the check box in tasks

https://github.com/user-attachments/assets/17bf909c-b028-48f3-a70d-9111b1883a14

**Comment by ewhang5** [comment]
> i'm still able to alter the reports in enterprises maybe also disabling the check box in tasks
> 
>  Screen_recording_20240729_150320.mp4

Hi @Okuro3499, I thought that enterprises is separate from teams. Do you think this would be a separate issue that I could tackle instead? Also, for tasks in teams, the checkbox is disabled already. It is still visible, but non-members cannot click on them.

**Comment by ewhang5** [comment]
@Okuro3499 I handled the enterprise reports.

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
