### PR TITLE
all: smoother dashboard (fixes #4664)

### LINKED ISSUE #4664: Separation between the icons and the label
In the menu the separation between the label and the icon is so much, we need join a little bit.
image

### PR DESCRIPTION
**Pull request by Kuljeet1998**
Fixes: #4664

image

### CODE REVIEW

**Review by deeppp15 — APPROVED** [review]

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
on a pixel 8 pro api 34 it again starts to overlap into the device status bar. maybe try not using fixed dimensions as this does not make it responsive for different screen
Screenshot_20241018_210004

**Comment by Kuljeet1998** [comment]
Hi Gideon this PR solves different issue: #4664

**Comment by Okuro3499** [comment]
> Hi Gideon this PR solves different issue: #4664 I will pick the logo issue again.

the logo issue is what needs to be solve in issue #4664. what does this solve?

**Comment by Okuro3499** [comment]
does not fix any issue

**Pull request closed without merging**
