### PR TITLE
all: smoother notifications translations (fixes #4479)

### LINKED ISSUE #4479: translate button texts in notification
image

### PR DESCRIPTION
**Pull request by Kuljeet1998**
Fixes: #4479 
image
image

### CODE REVIEW

**Review by Okuro3499 — APPROVED** [review]

**Comment by Kuljeet1998** [comment]
Follow up issue: https://github.com/open-learning-exchange/myplanet/issues/4483

**Comment by deeppp15** [comment]
Hey @Kuljeet1998 , this one is also crashing for me

 java.lang.NullPointerException: Missing required view with ID: org.ole.planet.myplanet:id/btnMarkAllAsRead
                                                                                                    	at org.ole.planet.myplanet.databinding.FragmentNotificationBinding.bind(FragmentNotificationBinding.java:113)
                                                                                                    	at org.ole.planet.myplanet.databinding.FragmentNotificationBinding.inflate(FragmentNotificationBinding.java:70)
                                                                                                    	at org.ole.planet.myplanet.ui.dashboard.notification.NotificationFragment.onCreateView(NotificationFragment.kt:52)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7073)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by Kuljeet1998** [comment]
Hi @deeppp15 try this after switching from master, this one should work. Lemme know if it still persists.

**Review by deeppp15 — APPROVED** [review]

**Comment by deeppp15** [comment]
> Hi @deeppp15 try this after switching from master, this one should work. Lemme know if it still persists.

@Kuljeet1998  Worked ! Thankyou

**Review by dogi — APPROVED** [review]

**Pull request merged**
