### PR TITLE
sync: smoother settings (fixes #4445)(fixes #4448)

### LINKED ISSUE #4445: sync pop up redesign
redesign for playstore to be able to select a  server
[121.webm](https://github.com/user-attachments/assets/30ab6bbc-0ea0-42b4-8991-8a4c8464c11e)

### LINKED ISSUE #4448: darkmode clear data button not visible
- Darkmode Clear Data Button not visible

image

_Originally posted by @deeppp15 in https://github.com/open-learning-exchange/myplanet/issues/4446#issuecomment-2364209057_

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #4445
[synced.webm](https://github.com/user-attachments/assets/f2dec177-f914-4524-ade1-6d96d5f11108)

roboscript autotest

https://github.com/user-attachments/assets/663c3547-4106-4417-81d5-b1deefb1bac6

### CODE REVIEW

**Review by Kuljeet1998 — APPROVED** [review]

**Comment by deeppp15** [comment]
- Darkmode Clear Data Button not visible

image

**Review by deeppp15 — APPROVED** [review]

**Review by AdhamElAsfar99 — DISMISSED** [review]
cloud spinner text not visible in light mode

[lightmode sync.webm](https://github.com/user-attachments/assets/1dd53dad-71d2-471e-956d-b1726b2f1310)

**Comment by Okuro3499** [comment]
> cloud spinner text not visible in light mode
> 
>  lightmode.sync.webm

Screenshot_20240920_220136

**Comment by deeppp15** [comment]
Fixes #4448

**Pull request merged**
