### PR TITLE
teams: smoother calendar translations (fixes #3936)

### LINKED ISSUE #3936: calendar showing wrong language
If you've recently switched languages, the calendar month will still show the previous language used.

image

### PR DESCRIPTION
**Pull request by rlam20**
image

### CODE REVIEW

**Comment by strawberrybread** [comment]
changing the language multiple times causes the tabs to stay in the previous language

image

**Comment by rlam20** [comment]
> changing the language multiple times causes the tabs to stay in the previous language
> 
> image

also the tabs will not always translate - will look into it

**Comment by rlam20** [comment]
> changing the language multiple times causes the tabs to stay in the previous language
> 
> image

this issue is already addressed, it is separate from the calendar

**Review by strawberrybread — APPROVED** [review]

**Review by ewhang5 — APPROVED** [review]

**Comment by Okuro3499** [comment]
fixes #3936

**Comment by rlam20** [comment]
image

**Review by Okuro3499 — APPROVED** [review]
[Screen_recording_20240830_172417.webm](https://github.com/user-attachments/assets/f5e8e597-7418-46c3-9786-8d75778bd7fa)

**Review by AdhamElAsfar99 — APPROVED** [review]

**Comment by deeppp15** [comment]
Need calendar language support for Somali and Nepali.

**Review by deeppp15 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
