### PR TITLE
dashboard: smoother survey dialog (fixes #4340)(fixes #4343)

### LINKED ISSUE #4340: mySurveys: incomplete surveys dialog is not scrollable
### Description

The length of the dialog box depends on the number of surveys listed. 
So in case there are 10 ,15 pending  surveys dialog box may be streched out of screen.

WhatsApp Image 2024-09-04 at 13 13 06_598681a3

### Suggestions
Could we implement a scrollable dialog box or maybe just display the number of pending surveys in the surveys tab

Syrvey proposal Active
Survey proposal

_Originally posted by @deeppp15 in https://github.com/open-learning-exchange/myplanet/issues/4336#issuecomment-2329617112_

### LINKED ISSUE #4343: change color for survey's dialog in darkmode
image

### PR DESCRIPTION
**Pull request by deeppp15**
### Description

Added Survey Adapter file and custom xml to create a scrollable dialog box.

### Features

- Survey List is scrollable
- Upon clicking a survey user is directed to that survey and dialog is closed.
- Also made the dialog box compatible with darkmode.

### Screenshots and Recording
WhatsApp Image 2024-09-06 at 13 48 39_49227851

WhatsApp Image 2024-09-06 at 13 48 39_9313b06a

https://github.com/user-attachments/assets/2dca6979-79f6-466f-aeff-8e4023651578

fixes #4340

### CODE REVIEW

**Review by Kuljeet1998 — APPROVED** [review]

**Review by AdhamElAsfar99 — APPROVED** [review]
It also fixes #4343

**Comment by deeppp15** [comment]
> It also fixes #4343

Thanks @AdhamElAsfar99

**Review by Okuro3499 — APPROVED** [review]

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
remove comments

**Comment by deeppp15** [comment]
> remove comments

Removed Comments @Okuro3499

**Review by dogi — APPROVED** [review]

**Pull request merged**
