### PR TITLE
resources: add pagination (fixes #3485)

### LINKED ISSUE #3485: pagination in resources
add a pagination filter to reduce cluttering of data

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #3485
https://github.com/open-learning-exchange/myplanet/assets/64019708/8dd6d19f-ef6f-4943-ae0a-704e1dbac548

### CODE REVIEW

**Review by rlam20 — COMMENTED** [review]
It looks good, but one suggestion: is it possible to make it so that every time you hit 'next' or 'previous' to swap pages, can you make it so you start at the top?

**Comment by Okuro3499** [comment]
@rlam20 you will now be able to scroll to on moving to a new page


https://github.com/open-learning-exchange/myplanet/assets/64019708/e975b411-fab8-4c37-abe3-20f9edebeff6

**Review by rlam20 — APPROVED** [review]

**Review by rlam20 — CHANGES_REQUESTED** [review]
When selecting 'all' it does not display all the files on the page. It only displays 10 resources at a time.

**Comment by dogi** [comment]
thx @Okuro3499

**Pull request closed without merging**
