### PR TITLE
courses: smoother dark mode (fixes #3999)

### LINKED ISSUE #3999: dark mode: change colors for courses
Areas to change: rethink text color in course description, rating course
Screenshot 2024-08-01 at 10 28 46 AM
Screenshot 2024-08-01 at 10 29 04 AM

### PR DESCRIPTION
**Pull request by ewhang5**
fixes #3999

### CODE REVIEW

**Comment by strawberrybread** [comment]
image

It's a little difficult to distinguish the review popup from the background since they are the same color. Could you maybe give it a border so that it's easier to see?

**Comment by ewhang5** [comment]
> image
> 
> It's a little difficult to distinguish the review popup from the background since they are the same color. Could you maybe give it a border so that it's easier to see?

Hi @strawberrybread, for my device, the background is shaded once the popup appears. I am unsure why your device looks this way. @Okuro3499 do you know what may be causing this difference?
Screenshot 2024-08-02 at 11 09 32 AM

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
it's difficult to read the text maybe make them white
Screenshot_20240802_200653

**Comment by Okuro3499** [comment]
> > image
> > It's a little difficult to distinguish the review popup from the background since they are the same color. Could you maybe give it a border so that it's easier to see?
> 
> Hi @strawberrybread, for my device, the background is shaded once the popup appears. I am unsure why your device looks this way. @Okuro3499 do you know what may be causing this difference? Screenshot 2024-08-02 at 11 09 32 AM

not sure what is causing that but if the colors are almost similar the may appear this way on different devices depending in the device graphics

**Comment by ewhang5** [comment]
@Okuro3499 I addressed your comment. Do you also have the same issue as Vivian?

**Comment by Okuro3499** [comment]
> @Okuro3499 I addressed your comment. Do you also have the same issue as Vivian?

no I don't have the same issue

**Review by Okuro3499 — APPROVED** [review]
I have approved and opened a pull request to make the icons and texts visible in dark mode across the entire application in #4025

**Review by strawberrybread — APPROVED** [review]

**Review by rlam20 — APPROVED** [review]

**Review by AdhamElAsfar99 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
