### PR TITLE
dashboard: smoother add resource dialog (fixes #4491)

### LINKED ISSUE #4491: Add resource dialog
## Description

Make this  add resource dialog darkmode compatible.

image

### PR DESCRIPTION
**Pull request by deeppp15**
## Description

Added darkmode compatible changes.  Open for color scheme suggesions. ( fixes #4491)

## Screenshot

image

### CODE REVIEW

**Review by Kuljeet1998 — APPROVED** [review]

**Comment by Okuro3499** [comment]
in light mode this is how it is in master
Screenshot_20240926_204632
vs how it is in this branch
Screenshot_20240926_204800

@deeppp15 do you think it would look better if it maintains the blue color in both dark and light modes

**Comment by deeppp15** [comment]
> in light mode this is how it is in master Screenshot_20240926_204632 vs how it is in this branch Screenshot_20240926_204800
> 
> @deeppp15 do you think it would look better if it maintains the blue color in both dark and light modes

Hi @Okuro3499 , what about this ? 
image

**Comment by Okuro3499** [comment]
@dogi @Mutugiii which one looks better?

**Review by Okuro3499 — APPROVED** [review]
@deeppp15 I reverted back to the first change you did looked better than the second change
[Screen_recording_20240930_181936.webm](https://github.com/user-attachments/assets/09900856-13b4-41b4-942a-2b8e8acafbdd)

**Review by dogi — APPROVED** [review]

**Pull request merged**
