### PR TITLE
all: smoother notifications (fixes #4457)

### LINKED ISSUE #4457: mark all as read button
`mark all as read` button still appears despite all notifications being marked as read
Screenshot_20240920_222651

### PR DESCRIPTION
**Pull request by Kuljeet1998**
Fixes: #4457 

image

### CODE REVIEW

**Comment by Okuro3499** [comment]
@Kuljeet1998 app crashes
[Screen_recording_20240925_203834.webm](https://github.com/user-attachments/assets/6e9d24d8-3293-42eb-ab3e-612533e03193)

```
FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 14725
java.lang.NullPointerException: Missing required view with ID: org.ole.planet.myplanet:id/btnMarkAllAsRead
	at org.ole.planet.myplanet.databinding.FragmentNotificationBinding.bind(FragmentNotificationBinding.java:113)
	at org.ole.planet.myplanet.databinding.FragmentNotificationBinding.inflate(FragmentNotificationBinding.java:70)
	at org.ole.planet.myplanet.ui.dashboard.notification.NotificationFragment.onCreateView(NotificationFragment.kt:52)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
@Kuljeet1998 app crashes
[Screen_recording_20240925_203834.webm](https://github.com/user-attachments/assets/6e9d24d8-3293-42eb-ab3e-612533e03193)

```
FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 14725
java.lang.NullPointerException: Missing required view with ID: org.ole.planet.myplanet:id/btnMarkAllAsRead
	at org.ole.planet.myplanet.databinding.FragmentNotificationBinding.bind(FragmentNotificationBinding.java:113)
	at org.ole.planet.myplanet.databinding.FragmentNotificationBinding.inflate(FragmentNotificationBinding.java:70)
	at org.ole.planet.myplanet.ui.dashboard.notification.NotificationFragment.onCreateView(NotificationFragment.kt:52)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Review by deeppp15 — APPROVED** [review]

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
mark all as read still appears even after all have been marked as read
[Screen_recording_20240926_205149.webm](https://github.com/user-attachments/assets/87476456-3652-4369-8ad4-dbb6467763b3)

**Comment by Kuljeet1998** [comment]
https://github.com/user-attachments/assets/5bb39bb9-d0d7-4155-8d66-4b9cc6462b93

**Review by deeppp15 — APPROVED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
