### PR TITLE
Add blinking hint arrow Fixes #929

### LINKED ISSUE #929: Hint for Scrollable Action bar

### PR DESCRIPTION
**Pull request by ChiragAwale**

### CODE REVIEW

**Comment by ChiragAwale** [comment]
@leomaxi @rrijal53

**Comment by rrijal53** [comment]
@ChiragAwale  fix merge conflict.

**Comment by ChiragAwale** [comment]
@rrijal53 done

**Comment by ChiragAwale** [comment]
Closed for now

**Pull request closed without merging**
