### PR TITLE
Server url format (Fixes #414)

### LINKED ISSUE #414: Server url
We can update the server url to user `/db`
Url format that we need to consider 
- `http://domain:port/db`
- `http://domain/db`
- `http://user:pass@domain/db`
- `http://user:pass@domain:port/db`

`db` shall be added while doing any database call so user can just put the url they are using to access planet application without need to remember different url pattern.
Usually it will not have any port on domain but we need to consider that sometime we might use server instance which will use different port than default 80/443 ports. Hence url should check does port number exist as well.

### PR DESCRIPTION
**Pull request by rrijal53**
The library not accepting url redirection, while using  ```domain/db``` . 
I don't found any option to enable redirection in lightcouch .
 Error :
screen shot 2018-12-12 at 7 19 51 pm

### CODE REVIEW

**Comment by yuviii** [comment]
This might help how to redirect if the url is moved.
need to add this in lightcouch library.
```
boolean redirect = false;

	// normally, 3xx is redirect
	int status = conn.getResponseCode();
	if (status != HttpURLConnection.HTTP_OK) {
		if (status == HttpURLConnection.HTTP_MOVED_TEMP
			|| status == HttpURLConnection.HTTP_MOVED_PERM
				|| status == HttpURLConnection.HTTP_SEE_OTHER)
		redirect = true;
	}

	System.out.println("Response Code ... " + status);

	if (redirect) {

		// get redirect url from "location" header field
		String newUrl = conn.getHeaderField("Location");

		// get the cookie if need, for login
		String cookies = conn.getHeaderField("Set-Cookie");

		// open the new connnection again
		conn = (HttpURLConnection) new URL(newUrl).openConnection();
		conn.setRequestProperty("Cookie", cookies);
		conn.addRequestProperty("Accept-Language", "en-US,en;q=0.8");						
		System.out.println("Redirect to URL : " + newUrl);

	}

```
For reference UrlConnection redirect sample
[https://www.mkyong.com/java/java-httpurlconnection-follow-redirect-example/](https://www.mkyong.com/java/java-httpurlconnection-follow-redirect-example/)

**Comment by rrijal53** [comment]
@leomaxi  @lmmrssa @yuviii  i've removed lightcouch and used retrofit and able to sync using /db url pattern.
Please check it and give feedback , then we also need to change upload manager, so we can upload results using /db url.

**Comment by rrijal53** [comment]
@leomaxi  working in my case, looking into it further... 
```Planet```
screen shot 2018-12-19 at 8 04 35 pm

```My planet```
screenshot_1545229087

**Comment by yuviii** [comment]
@rrijal53 @leomaxi not working in my case for the submission
**i did**
 - logged in with different user
- clicked in submission
**App get crashed with following log message**
screenshot 2018-12-21 19 39 07

**Comment by lmmrssa** [comment]
With this branch now `db` and `versions` call are working. But there are still issues with sync.
* User detail updated on planet is not synced on myplanet
* User shelf is always replace by myplanet on planet when clicked on Refresh icon. Even when things are added on planet.
* When clicked on sync shelf does not change One removed from planet still remains on myplanet and One removed on myplanet also remains on planet.

**Comment by leomaxi** [comment]
Works for me. more test required.. @yuviii , @lmmrssa

**Pull request merged**
