### PR TITLE
Manage mode added (Fixes #830)

### LINKED ISSUE #830: Make manager login possible
We are not syncing **manager** on `tablet_users` database. And we do not want manager to be synced in general.
But sometimes manager might require to login on tablet. So we want to have a button from where people can add manager account on tablet. It should be hidden somewhere inside Setting (Gear Icon) so it is not something normally people will try to go for.
Once people try to add manager account we should try to trigger `_users` database to see if credentials are valid. Also we need to check if user credential is of manager, **isUserAdmin** and **manager** role should help to identify.
Then we save it on local database but manager users are never to be synced.
After that manager should be able to login on that tablet as generally they do with other learner users.

### PR DESCRIPTION
**Pull request by rrijal53**
Now we can add manager from setting.

Screenshot_1558627248
Screenshot_1558627250

### CODE REVIEW

**Comment by rrijal53** [comment]
@leomaxi @leomaxi  
Response from url/db/ does not contains salt and derived key , so i'm having trouble with manager authentication any suggestions?

Screen Shot 2019-05-26 at 21 44 42


Screen Shot 2019-05-26 at 21 44 50

**Comment by leomaxi** [comment]
I noticed too, how does the satellite help here @all

**Comment by rrijal53** [comment]
@leomaxi  i've made the changes as you said please review again , and i'll fix code climate then.

**Comment by rrijal53** [comment]
@leomaxi i will test and fix that in another PR.

**Pull request merged**
