### PR TITLE
all: smoother screen mode (fixes #4286)

### LINKED ISSUE #4286: notification bar coincides with app
Works fine until notifications are accessed. 
After notifications are viewed, the app and notification bar coincides.
Device: OnePlus 6t

https://github.com/user-attachments/assets/5a4b32f1-fb5b-48f2-90d7-2ec863aaec01

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #4286
[Screen_recording_20241001_182651.webm](https://github.com/user-attachments/assets/7394a370-fbed-4fe5-9211-fe60a76605c3)

### CODE REVIEW

**Comment by Kuljeet1998** [comment]
Should we adjust the sidebar full-screen too? To make the UI more consistent.

image

**Comment by Okuro3499** [comment]
> Should we adjust the sidebar full-screen too? To make the UI more consistent.
> 
> image

yes I can do that

**Comment by Okuro3499** [comment]
show chat data even when keyboard is shown
Screenshot_20241002_150550

**Comment by Okuro3499** [comment]
> Should we adjust the sidebar full-screen too? To make the UI more consistent.
> 
> image

@Kuljeet1998 we are using the mikepenz. library for the drawer and this is the standard for the library we can figure out how to override it in another pull request https://github.com/mikepenz/MaterialDrawer?tab=readme-ov-file#screenshots-

**Review by dogi — APPROVED** [review]

**Pull request merged**
