### PR TITLE
teams: smoother strings (fixes #3926)

### LINKED ISSUE #3926: teams/enterprise: incomplete translations

### PR DESCRIPTION
**Pull request by rlam20**
image
image

### CODE REVIEW

**Comment by Okuro3499** [comment]
@rlam20 based on title how does the changes in this pr fix translations

**Comment by rlam20** [comment]
> @rlam20 based on title how does the changes in this pr fix translations

i used fix translations because previously, all the tabs under teams/enterprises wouldn't translate over to the selected language. i can rename it to 'completed translations' or something similar

**Comment by strawberrybread** [comment]
image

the tabs aren't translating for me

**Comment by Okuro3499** [comment]
> > @rlam20 based on title how does the changes in this pr fix translations
> 
> i used fix translations because previously, all the tabs under teams/enterprises wouldn't translate over to the selected language. i can rename it to 'completed translations' or something similar

seems you are only removing `MainApplication.` which refers to where the context is imported from which does not influence anything on translations. maybe changing the pr title to what it actually does would make it ok

**Review by Okuro3499 — APPROVED** [review]

**Review by ewhang5 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Pull request merged**
