### PR TITLE
Fixes #895 Https - Http Selector modified

### LINKED ISSUE #895: Allowed to add http even when we have http selector
There is protocol selector **http** and **https** but still server url needs to have http. If we remove it then it does not allow you to sync.

### PR DESCRIPTION
**Pull request by ChiragAwale**
Fixes #895 
This is done without affecting the preexisting code too much, keeping it to a bare minimum. Please have a look.
@lmmrssa

### CODE REVIEW

**Comment by rrijal53** [comment]
@ChiragAwale  
It doesnot work when someone unknowingly adds http/s in url . So
please add hint, something like `enter url (Eg. 192.168.100.17)` - without http/s
or you can disable sync button when there is https:// in the url 
Screenshot_1562856061

**Comment by ChiragAwale** [comment]
@rrijal53 gotcha

**Comment by ChiragAwale** [comment]
@rrijal53 I added the hint, I can work on disabling the sync too, do you want me to do that?

**Comment by leomaxi** [comment]
Screenshot 2019-07-16 at 10 06 00 AM

**Pull request merged**
