### PR TITLE
Open resource on dashboard item clicked and more button to open detail (Fixes #411)

### LINKED ISSUE #411: Open Resource Media
When you open Resource from dashboard, it should open media and other detail should show by some button. If you move from Library then we can show details and then media.

### PR DESCRIPTION
**Pull request by rrijal53**
screenshot_1544364559

### CODE REVIEW

**Comment by yuviii** [comment]
Getting app crashed
**I did**
 - selected three items from library page
 - clicked add to library
 - navigate to home
 - clicked third item it opened ok
 - when i clicked first or second item then app crashed

**Below is the error message from logcat**

screenshot 2018-12-09 23 19 11

**Comment by yuviii** [comment]
Switching in this branch is giving the gradle build failure. Producing error with the exoplayer dependency version not matched 2.8.3 however with 2.7.2 its working fine.

screenshot 2018-12-11 00 02 13

**Comment by rrijal53** [comment]
@yuviii It is showing this error in travis too, i'm looking for the issue to fix it.

**Comment by rrijal53** [comment]
@leomaxi  yes, trying to fix since yesterday but unable to fix it .

**Pull request merged**
